import type { Metadata } from "next";
import "@/styles/globals.css";
import { Provider } from "@/components/theme/provider";
import { Indicator } from "@/components/theme/indicator";
import { cn } from "@/lib/utils";
import { fontSans } from "@/lib/fonts";
import { Header } from "@/components/header/header";

export let metadata: Metadata = {
  title: "Prometheus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Provider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <div className="relative flex min-h-screen flex-col">
            <div className="flex-1">{children}</div>
          </div>
          <Indicator />
        </Provider>
      </body>
    </html>
  );
}
